V5.ResGTrackRelated = {
  "global": {
    "__copyMsg_failureFromFlash": "Copy failed, your browser doesn't support Adobe Flash or it's out of date.",
    "__copyMsg_nothing": "No result available for copy.",
    "__copyMsg_success": "Copied successfully, text has been added to the clipboard.",
    "__editorCaptcha_error": "Wrong captcha, please re-enter.",
    "__editorCaptcha_inputCode": "Please enter captcha",
    "__editorCaptcha_reload": "Try another",
    "__editorCarrier_auto": "Auto-detect carrier",
    "__editorCarrier_autoTips": "The system will auto-identify tracking number and retrieves information from respective carrier",
    "__editorCarrier_commonCarrier": "My carriers",
    "__editorCarrier_desc": "Tips: Under normal conditions, the system enables to auto-detect and identify the shipping carrier, country of origin / destination. It doesn't require manual operation. But due to worldwide logistics providers' tracking access is being extremely complex. Our auto-detection accuracy rate isn't 100%. Therefore, if under any circumstances, our system has identified the carrier incorrectly or shows as unknown, please designate shipping carrier manually.",
    "__editorCarrier_hint": "Search postal carrier/express courier or country",
    "__editorCarrier_historyTitle": "Search history",
    "__editorCarrier_searchNoFound": "No matching carrier found.",
    "__editorTrack_hint": "Enter up to 40 numbers, one per line.",
    "__editorTrack_msgCharacter": "Invalid, tracking number must be a combination of alphanumeric characters of 5-50 characters in length.",
    "__editorTrack_msgExceed": "Maximum is 40 numbers per time! The excess of numbers will be ignored! Do you want to continue?",
    "__editorTrack_msgFilter": "No filtered number, please check your input or click \"TRACK\" directly.",
    "__editorTrack_msgIllegal": "Your input is invalid, please ensure the tracking number is a combination of alphanumeric characters.",
    "__editorTrack_msgNull": "Please enter your tracking number.",
    "__editorTrackButton_carrier": "Carrier",
    "__editorTrackButton_carrierTips": "Select carrier",
    "__tool_compress": "Collapse",
    "__tool_expand": "Expand",
    "__tool_modifyCarrierTips": "If auto-detection is incorrect or unknown, please designate carrier manually.",
    "__tool_officialWebsiteTips": "Go to the carrier's official website",
    "__tool_reTrackErrorOneTips": "Re-track the tracking errors",
    "__toolCopy_copyDetailsTips": "Copy detailed tracking results for all numbers",
    "__toolCopy_copyLink": "Copy Link",
    "__toolCopy_copyLinkTips": "This link redirects to the current tracking result page",
    "__toolCopy_copyResult": "Copy Result",
    "__trackResult_formatCacheTime": "Cache Time: {0}",
    "__trackResult_formatConsuming": "Tracking Consuming: {0} ms",
    "__trackResult_formatDays": "{0} Days",
    "__trackResult_formatLastEvent": "Latest Event -- {0}",
    "__trackResult_textHasError": "Sorry, a tracking error has occurred. Please retry.",
    "__trackResult_textPleaseWait": "Tracking, please wait for a moment…",
    "__trackResult_textTimeout": "Sorry, tracking is timeout. Please retry.",
    "__trackResult_textTracking": "Tracking",
    "__trackResult_textTranslating": "Translating, please wait for a moment…",
    "__trackRetMsg_needParmMultiple": "Maybe your number belongs to",
    "__trackRetMsg_ret0": "Abnormal request (0), please contact the system administrator.",
    "__trackRetMsg_ret2": "Abnormal request (2), please retry.",
    "__trackRetMsg_ret3": "Sorry, the system is currently being updated, please try again later.",
    "__trackRetMsg_ret4": "Abnormal request (4), please retry.",
    "__trackRetMsg_ret5": "Your tracking is too frequent, please try again later.",
    "__trackRetMsg_ret6": "Abnormal request (6), please contact the system administrator.",
    "__trackRetMsg_ret7": "Abnormal request (7), please contact the system administrator.",
    "__trackRetMsg_ret8": "Our firewall detects abnormal activity from your IP. Please enter the captcha to unblock it.",
    "__trackRetMsg_ret9": "Abnormal request (9), please contact the system administrator.",
    "__translate_aim": "Target Language",
    "__translate_translate": "Translate"
  },
  "items": []
}
V5.ResGTrackRelated.items.itemsDict = new Dictionary();
$.each(V5.ResGTrackRelated.items, function (i, item) { 
	V5.ResGTrackRelated.items.itemsDict.put(Number(item.key), item);
});