var appManager = angular.module('appManager', [
    'ngMessages'
    , 'ngResource'
    , 'ngRoute'
    , 'ui.router'
    , 'ngSanitize'
    , 'ui-notification'
    , 'naif.base64'
    , 'base64'
    , 'ui.bootstrap'
    , 'angular-datepicker'
    , 'bw.paging'
    //, '720kb.datepicker'
    , 'ngWYSIWYG'
    , 'youtube-embed'
    , 'ngTagsInput'
    , 'ngFileSaver'
    , 'ngFileUpload'
    , 'angularFileInput'
    , 'ngEmbed'
    , 'ui.bootstrap.datetimepicker'
    , 'ngAudio'
    , 'rzModule'
]);